version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ecommerce-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
    restart: always

volumes:
  postgres_data: