version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432" # Sol taraf senin bilgisayarın (localhost), sağ taraf Container'ın içi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: